/**
 * Rushia DL Cookie Helper - Background Service Worker
 * Rushia DL専用の軽量Cookie取得拡張機能
 */

// 許可されたドメインリスト（セキュリティのため）
const ALLOWED_DOMAINS = [
  'rushiadl.holosco.pe',
  'localhost',
  '127.0.0.1',
  '0.0.0.0'
];

/**
 * ドメインが許可されているかチェック
 * @param {string} url - チェックするURL
 * @returns {boolean}
 */
function isAllowedDomain(url) {
  try {
    const urlObj = new URL(url);
    return ALLOWED_DOMAINS.some(domain => 
      urlObj.hostname === domain || 
      urlObj.hostname.endsWith('.' + domain)
    );
  } catch (e) {
    return false;
  }
}

/**
 * Chrome Cookie形式をNetscape形式に変換
 * @param {chrome.cookies.Cookie[]} cookies
 * @returns {string[][]}
 */
function jsonToNetscapeMapper(cookies) {
  return cookies.map(({ domain, expirationDate, path, secure, name, value }) => {
    // Netscape形式では、ドメインはそのまま（.で始まる場合はそのまま）
    // 2番目のフィールドがincludeSubDomain（TRUE/FALSE）
    const includeSubDomain = !!domain?.startsWith('.');
    const expiry = expirationDate ? Math.floor(expirationDate).toString() : '0';
    const arr = [
      domain || '',  // ドメインはそのまま（.を含む）
      includeSubDomain ? 'TRUE' : 'FALSE',
      path || '/',
      secure ? 'TRUE' : 'FALSE',
      expiry,
      name || '',
      value || ''
    ];
    return arr;
  });
}

/**
 * CookieをNetscape形式のテキストに変換
 * @param {chrome.cookies.Cookie[]} cookies
 * @returns {string}
 */
function convertToNetscapeFormat(cookies) {
  const netscapeTable = jsonToNetscapeMapper(cookies);
  const text = [
    '# Netscape HTTP Cookie File',
    '# https://curl.haxx.se/rfc/cookie_spec.html',
    '# This is a generated file! Do not edit.',
    '# Generated by Rushia DL Cookie Helper',
    '',
    ...netscapeTable.map((row) => row.join('\t')),
    '' // Add a new line at the end
  ].join('\n');
  return text;
}

/**
 * 指定されたドメインのCookieを取得
 * @param {string} domain - ドメイン名（例: 'youtube.com'）
 * @returns {Promise<chrome.cookies.Cookie[]>}
 */
async function getAllCookies(domain) {
  try {
    // ドメインが指定されている場合
    if (domain) {
      // 完全一致とサブドメインの両方を取得
      const exactCookies = await chrome.cookies.getAll({ domain: domain });
      const subdomainCookies = await chrome.cookies.getAll({ domain: '.' + domain });

      // 重複を除去
      const cookieMap = new Map();
      [...exactCookies, ...subdomainCookies].forEach(cookie => {
        const key = `${cookie.domain}|${cookie.name}|${cookie.path}`;
        if (!cookieMap.has(key)) {
          cookieMap.set(key, cookie);
        }
      });

      return Array.from(cookieMap.values());
    } else {
      // ドメインが指定されていない場合は全Cookieを取得
      return await chrome.cookies.getAll({});
    }
  } catch (error) {
    console.error('Cookie取得エラー:', error);
    throw error;
  }
}

/**
 * 外部からのメッセージを受け取る
 */
chrome.runtime.onMessageExternal.addListener(
  (request, sender, sendResponse) => {
    // セキュリティチェック: 許可されたドメインからのみ受け付ける
    if (!sender.url || !isAllowedDomain(sender.url)) {
      console.warn('許可されていないドメインからのリクエスト:', sender.url);
      sendResponse({ 
        error: 'Unauthorized domain',
        message: 'この拡張機能は許可されたドメインからのみ使用できます。'
      });
      return;
    }

    // Cookie取得リクエストを処理
    if (request.action === 'exportCookies') {
      const domain = request.domain || 'youtube.com';
      const format = request.format || 'netscape';

      getAllCookies(domain)
        .then(cookies => {
          if (format === 'netscape') {
            const cookieText = convertToNetscapeFormat(cookies);
            sendResponse({ 
              success: true,
              cookies: cookieText,
              count: cookies.length,
              domain: domain
            });
          } else if (format === 'json') {
            sendResponse({ 
              success: true,
              cookies: JSON.stringify(cookies, null, 2),
              count: cookies.length,
              domain: domain
            });
          } else {
            sendResponse({ 
              error: 'Invalid format',
              message: 'サポートされている形式: netscape, json'
            });
          }
        })
        .catch(error => {
          console.error('Cookie取得エラー:', error);
          sendResponse({ 
            error: error.message || 'Cookie取得に失敗しました',
            message: error.toString()
          });
        });

      return true; // 非同期レスポンス用
    }

    // pingリクエスト（拡張機能の存在確認用）
    if (request.action === 'ping') {
      sendResponse({ 
        success: true,
        message: 'Rushia DL Cookie Helper is ready',
        version: chrome.runtime.getManifest().version
      });
      return true;
    }

    // 不明なアクション
    sendResponse({ 
      error: 'Unknown action',
      message: 'サポートされているアクション: exportCookies, ping'
    });
  }
);

// 拡張機能のインストール/更新時のログ
chrome.runtime.onInstalled.addListener((details) => {
  if (details.reason === 'install') {
    console.log('Rushia DL Cookie Helper がインストールされました');
  } else if (details.reason === 'update') {
    console.log('Rushia DL Cookie Helper が更新されました');
  }
});

